# Generated by Django 4.2.27 on 2025-12-29 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PalmTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم النخلة')),
                ('location_lat', models.FloatField(blank=True, null=True, verbose_name='خط العرض')),
                ('location_lng', models.FloatField(blank=True, null=True, verbose_name='خط الطول')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='diagnoses/%Y/%m/%d/', verbose_name='الصورة المرفوعة')),
                ('result_label', models.CharField(max_length=100, verbose_name='نتيجة التشخيص')),
                ('confidence_score', models.FloatField(verbose_name='نسبة الثقة')),
                ('ai_recommendation', models.TextField(blank=True, null=True, verbose_name='توصية المساعد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('palm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='palm_app.palmtree')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
