# Generated by Django 4.2.27 on 2025-12-30 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('palm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={},
        ),
        migrations.RenameField(
            model_name='palmtree',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='ai_recommendation',
        ),
        migrations.RemoveField(
            model_name='palmtree',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='palmtree',
            name='location_lng',
        ),
        migrations.AddField(
            model_name='palmtree',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='palmtree',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='confidence_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='image',
            field=models.ImageField(upload_to='diagnosis/'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='result_label',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='palmtree',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
